### ISSUE TITLE
libX11 isn't declared as a dependency

### ISSUE THREAD

**Issue by Inatigerdream** [withinboredom/system-76-keyboards#28] opened 2021-01-22 03:49 UTC
All of the commands and installation worked fine but my keyboard did not change. Tried reinstalling and restarting my Oryx Pro a couple of times. Not sure how to be more helpful sorry.

**Comment by brandon-clair** [comment] 2021-01-22 20:02
Likewise.

Running `tail -f /var/log/syslog` while executing `sudo systemctl restart keyboard-colors` gives me this:
```
Jan 22 11:59:45 oryx systemd[1]: Started System76 Keyboard Colors.
Jan 22 11:59:45 oryx keyboard-color[9559]: Unhandled exception. System.DllNotFoundException: Unable to load shared library 'libX11' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibX11: cannot open shared object file: No such file or directory
Jan 22 11:59:45 oryx keyboard-color[9559]:    at keyboards.Installer.XOpenDisplay(String displayName)
Jan 22 11:59:45 oryx keyboard-color[9559]:    at keyboards.Installer.CheckAccessToDisplay(String d)
Jan 22 11:59:45 oryx keyboard-color[9559]:    at keyboards.Installer.RootHasPermission()
Jan 22 11:59:45 oryx keyboard-color[9559]:    at keyboards.Program.GetFilters(IConfiguration configuration, Boolean dim, IControlContainer container)
Jan 22 11:59:45 oryx keyboard-color[9559]:    at keyboards.Program.GetKeyboard(IControlContainer container, IConfiguration configuration)
Jan 22 11:59:45 oryx keyboard-color[9559]:    at keyboards.Program.RunOrInstall(Options options)
Jan 22 11:59:45 oryx keyboard-color[9559]:    at keyboards.Program.<>c.<Main>b__7_2(RunOptions o)
Jan 22 11:59:45 oryx keyboard-color[9559]:    at CommandLine.ParserResultExtensions.MapResult[T1,T2,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 notParsedFunc)
Jan 22 11:59:45 oryx keyboard-color[9559]:    at keyboards.Program.Main(String[] args)
Jan 22 11:59:46 oryx systemd[1]: keyboard-colors.service: Main process exited, code=dumped, status=6/ABRT
Jan 22 11:59:46 oryx systemd[1]: keyboard-colors.service: Failed with result 'core-dump'.
```

**Comment by withinboredom** [comment] 2021-01-22 22:25
You need to ensure the libX11 library is installed. The deb file doesn't declare it as a dependency. It's used to detect the screen going to sleep and turning off the keyboard.

**Comment by withinboredom** [comment] 2021-01-22 22:29
Duplicate of #25

**Closed as completed by withinboredom** 2021-01-22 22:29 UTC
